### ISSUE TITLE
请教一下如何配置开发和编译环境？

### ISSUE THREAD

**Issue by defineconst** [WuZixing/Geo3DML-CPP#1]
您好，谢谢发布的Geo3DML代码资料，请问如何搭建一下开发环境才能读取、展示Geo3DML，您是使用VTK来展示是吧？没有C++的基础该如何弄？如果用VTK读取和展示应该如何配置开发环境了？谢谢！

**Comment by WuZixing** [comment]
这个SDK是C++写的，只能用在C++项目里。如果只考虑可视化引擎，VTK有 python 接口可以调用，但是读写Geo3DML就需要自己另外实现。VTK的使用还请参考它自己的材料。
